### PR TITLE
Visibility for all langs

### PR DESCRIPTION
**Pull request by DrParadox7**
Adds changes in color for the Blast Furnace and Steam Boiler to all languages

GTNewHorizons/GT-New-Horizons-Modpack#9180

### CODE REVIEW

**Review by Dream-Master — APPROVED** [review]

**Comment by Dream-Master** [comment]
this looks ok
image
but this doesent
image
any idea @DrParadox7

**Comment by mitchej123** [comment]
We should probably just adjust it in the GUI instead of the name then

**Comment by Dream-Master** [comment]
wondering why coke oven use rc texture and blast furnace not

**Comment by Dream-Master** [comment]
image

**Comment by DrParadox7** [comment]
> We should probably just adjust it in the GUI instead of the name then

There's no work around for this it seems. We either do that or scrap my Pull Requests.

> wondering why coke oven use rc texture and blast furnace not

Blast Furnace uses the Furnace GUI, while Coke Oven uses its own.

**Pull request merged**
