### PR TITLE
Machine names are visible once more

### PR DESCRIPTION
**Pull request by DrParadox7**
Addresses GTNewHorizons/GT-New-Horizons-Modpack#9180

### CODE REVIEW

**Comment by mitchej123** [comment]
Hmm, I worry this will not display properly for people who have a texturepack that overrides the GUIs and uses the vanilla GUI...  How can we make it work with both?

**Comment by DrParadox7** [comment]
I don't know of many texture pack that override the langs and if they do, they would only change a couple of entries, not all.
This is usually only done when their redesigned GUI make text illegible just like this case.

It shouldn't an issue

**Comment by DrParadox7** [comment]
Black is an option:
image
image

**Comment by mitchej123** [comment]
It's fine, I'm sure most people use the default GUIs.   I don't, so I can just adjust it to deal with it locally.  I'll look into a config option.

**Review by mitchej123 — APPROVED** [review]

**Comment by bombcar** [comment]
> It's fine, I'm sure most people use the default GUIs. I don't, so I can just adjust it to deal with it locally. I'll look into a config option.

There’s work being done on a more generic “dark ui” which can move the font color out perhaps.

**Pull request merged**
