### PR TITLE
Update EntityLocomotiveSteamMagic.java

### PR DESCRIPTION
**Pull request by GregoriusT**
Fixed Thaumcraft dependency, which I did not notice before.

I used the Github Editor this time because nothing I did helped my ability to push to my own motherfucking fork... I did pulls, i did force pulls, I did rebases, i did hard resets, and I still cant commit and push to my own damn fork on github...

### CODE REVIEW

**Comment by GregoriusT** [comment]
Okay something is severely broken with this PR if the build and test task fails at this point...

**Review by serenibyss — APPROVED** [review]
Approving since I can confirm that this fixes the Thaumcraft dep issue.

I'm not sure why the CI task is failing, but it is not failing for me locally either so I agree that its likely something strange with the fork or an unrelated issue

**Comment by Glease** [comment]
CI failed because a village generated at spawn with a rolling machine (out of sheer luck). rolling machine ask for a RF thing to store power, which is stripped due to RF API somehow not present on classpath.

**Comment by GregoriusT** [comment]
Wait that means my PREVIOUS PR had Issues because I made that replacement function for the EnergyStorage @Optional without making sure there is a fallback...

I hate how you can call functions behind an if statement just fine, but as soon as a constructor merely exists that is when the classloader will screw you over...

Anyways, it does not have anything to do with this PR luckily...

So, to fix that EnergyStorage thing, the function cant be @Optional but the Constructor must be called inside of an @Optional Method or else the ClassLoader will crash. Guess there needs to be another layer, this time with a trycatch for NoSuchMethodError.

**Comment by Dream-Master** [comment]
can we add cofh as dependencie or just only for compiling ?

**Comment by GregoriusT** [comment]
CoFH is only a compile time dependency with this, railcraft can now startup MC all alone by itself once it is merged.

The EnergyStorage Class thing is unrelated to this, it was just a coincidence that it got missed in a PREVIOUS pull request. ;)

**Pull request merged**
