### PR TITLE
Fix external drain from railcraft tank never worked

### PR DESCRIPTION
**Pull request by GlodBlock**
i am curious about why nobody notice that is broken

### CODE REVIEW

**Comment by Connor-Colenso** [comment]
Could you make this title a bit more descriptive for the changelog? Thanks.

**Comment by GlodBlock** [comment]
done

**Review by Connor-Colenso — APPROVED** [review]
Thanks.

**Comment by chochem** [comment]
what do you mean nobody noticed? we all just assumed that is how its supposed to work. If I understand correctly you also just fixed this ticket? https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10849

**Comment by GlodBlock** [comment]
no that ticket is about buffing the internal drain of the valve so it has nothing to do with this pr.

**Comment by chochem** [comment]
no its about having any option for higher throughput really. buffing internal was just the proposal because everyone knows that external doesnt apply :P

**Comment by chochem** [comment]
well I will just post it there for now and ask. but pretty sure that will satisfy the player

**Pull request merged**
